services:
  backend:
    build: ./backend
    container_name: doctor_location_backend
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - eh_postgres
    networks:
      - doctor_network

  eh_postgres:
    image: postgres:15
    container_name: eh_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - eh_pgdata:/var/lib/postgresql/data
    networks:
      - doctor_network

networks:
  doctor_network:
    driver: bridge

volumes:
  eh_pgdata:
