services:
  eh_postgres:
    image: postgres:15
    container_name: eh_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ehospital
    ports:
      - "5432:5432"

  flask_backend:
    build: .
    container_name: doctor_location_backend
    ports:
      - "5000:5000"
    depends_on:
      - eh_postgres
